export type TaskStatus = 'TODO' | 'IN_PROGRESS' | 'DONE';

export interface Task {
    id: number;
    title: string;
    description?: string;
    status: TaskStatus;
    dueDate?: string;
}

// For create and update requests (id is generated by backend)
export interface TaskCreateRequest {
    title: string;
    description?: string;
    status?: TaskStatus;
    dueDate?: string;
}

export interface TaskUpdateRequest {
    title: string;
    description?: string;
    status: TaskStatus;
    dueDate?: string;
}